# Generated by Django 5.0.5 on 2024-05-07 14:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField()),
                ('info', models.CharField()),
                ('deadline', models.DateField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='user.user')),
                ('members', models.ManyToManyField(related_name='members', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proid', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=100)),
                ('deadline', models.CharField(max_length=50)),
                ('updated_time', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='incomplete')),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_to', to='user.user')),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectid', to='project.project')),
                ('reqid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reqid', to='project.requirement')),
            ],
        ),
    ]
