# Generated by Django 5.0.5 on 2024-05-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('phone', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
    ]
